// Code generated by ent, DO NOT EDIT.

package tasks

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tasks type in the database.
	Label = "tasks"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskName holds the string denoting the taskname field in the database.
	FieldTaskName = "task_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the tasks in the database.
	Table = "tasks"
)

// Columns holds all SQL columns for tasks fields.
var Columns = []string{
	FieldID,
	FieldTaskName,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Tasks queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskName orders the results by the taskName field.
func ByTaskName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
