// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rest_api/ent/predicate"
	"rest_api/ent/tasks"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTasks = "Tasks"
)

// TasksMutation represents an operation that mutates the Tasks nodes in the graph.
type TasksMutation struct {
	config
	op            Op
	typ           string
	id            *int
	taskName      *string
	status        *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Tasks, error)
	predicates    []predicate.Tasks
}

var _ ent.Mutation = (*TasksMutation)(nil)

// tasksOption allows management of the mutation configuration using functional options.
type tasksOption func(*TasksMutation)

// newTasksMutation creates new mutation for the Tasks entity.
func newTasksMutation(c config, op Op, opts ...tasksOption) *TasksMutation {
	m := &TasksMutation{
		config:        c,
		op:            op,
		typ:           TypeTasks,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTasksID sets the ID field of the mutation.
func withTasksID(id int) tasksOption {
	return func(m *TasksMutation) {
		var (
			err   error
			once  sync.Once
			value *Tasks
		)
		m.oldValue = func(ctx context.Context) (*Tasks, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Tasks.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTasks sets the old Tasks of the mutation.
func withTasks(node *Tasks) tasksOption {
	return func(m *TasksMutation) {
		m.oldValue = func(context.Context) (*Tasks, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TasksMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TasksMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Tasks entities.
func (m *TasksMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TasksMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TasksMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Tasks.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTaskName sets the "taskName" field.
func (m *TasksMutation) SetTaskName(s string) {
	m.taskName = &s
}

// TaskName returns the value of the "taskName" field in the mutation.
func (m *TasksMutation) TaskName() (r string, exists bool) {
	v := m.taskName
	if v == nil {
		return
	}
	return *v, true
}

// OldTaskName returns the old "taskName" field's value of the Tasks entity.
// If the Tasks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TasksMutation) OldTaskName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTaskName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTaskName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTaskName: %w", err)
	}
	return oldValue.TaskName, nil
}

// ResetTaskName resets all changes to the "taskName" field.
func (m *TasksMutation) ResetTaskName() {
	m.taskName = nil
}

// SetStatus sets the "status" field.
func (m *TasksMutation) SetStatus(b bool) {
	m.status = &b
}

// Status returns the value of the "status" field in the mutation.
func (m *TasksMutation) Status() (r bool, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Tasks entity.
// If the Tasks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TasksMutation) OldStatus(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *TasksMutation) ResetStatus() {
	m.status = nil
}

// Where appends a list predicates to the TasksMutation builder.
func (m *TasksMutation) Where(ps ...predicate.Tasks) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TasksMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TasksMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Tasks, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TasksMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TasksMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Tasks).
func (m *TasksMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TasksMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.taskName != nil {
		fields = append(fields, tasks.FieldTaskName)
	}
	if m.status != nil {
		fields = append(fields, tasks.FieldStatus)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TasksMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tasks.FieldTaskName:
		return m.TaskName()
	case tasks.FieldStatus:
		return m.Status()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TasksMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tasks.FieldTaskName:
		return m.OldTaskName(ctx)
	case tasks.FieldStatus:
		return m.OldStatus(ctx)
	}
	return nil, fmt.Errorf("unknown Tasks field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TasksMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tasks.FieldTaskName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTaskName(v)
		return nil
	case tasks.FieldStatus:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	}
	return fmt.Errorf("unknown Tasks field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TasksMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TasksMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TasksMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Tasks numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TasksMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TasksMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TasksMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Tasks nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TasksMutation) ResetField(name string) error {
	switch name {
	case tasks.FieldTaskName:
		m.ResetTaskName()
		return nil
	case tasks.FieldStatus:
		m.ResetStatus()
		return nil
	}
	return fmt.Errorf("unknown Tasks field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TasksMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TasksMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TasksMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TasksMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TasksMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TasksMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TasksMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Tasks unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TasksMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Tasks edge %s", name)
}
