// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rest_api/ent/tasks"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Tasks is the model entity for the Tasks schema.
type Tasks struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TaskName holds the value of the "taskName" field.
	TaskName string `json:"taskName,omitempty"`
	// Status holds the value of the "status" field.
	Status       bool `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tasks) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tasks.FieldStatus:
			values[i] = new(sql.NullBool)
		case tasks.FieldID:
			values[i] = new(sql.NullInt64)
		case tasks.FieldTaskName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tasks fields.
func (t *Tasks) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tasks.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case tasks.FieldTaskName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field taskName", values[i])
			} else if value.Valid {
				t.TaskName = value.String
			}
		case tasks.FieldStatus:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				t.Status = value.Bool
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tasks.
// This includes values selected through modifiers, order, etc.
func (t *Tasks) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// Update returns a builder for updating this Tasks.
// Note that you need to call Tasks.Unwrap() before calling this method if this Tasks
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Tasks) Update() *TasksUpdateOne {
	return NewTasksClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Tasks entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Tasks) Unwrap() *Tasks {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tasks is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Tasks) String() string {
	var builder strings.Builder
	builder.WriteString("Tasks(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("taskName=")
	builder.WriteString(t.TaskName)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", t.Status))
	builder.WriteByte(')')
	return builder.String()
}

// TasksSlice is a parsable slice of Tasks.
type TasksSlice []*Tasks
