// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rest_api/ent/tasks"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TasksCreate is the builder for creating a Tasks entity.
type TasksCreate struct {
	config
	mutation *TasksMutation
	hooks    []Hook
}

// SetTaskName sets the "taskName" field.
func (tc *TasksCreate) SetTaskName(s string) *TasksCreate {
	tc.mutation.SetTaskName(s)
	return tc
}

// SetStatus sets the "status" field.
func (tc *TasksCreate) SetStatus(b bool) *TasksCreate {
	tc.mutation.SetStatus(b)
	return tc
}

// SetID sets the "id" field.
func (tc *TasksCreate) SetID(i int) *TasksCreate {
	tc.mutation.SetID(i)
	return tc
}

// Mutation returns the TasksMutation object of the builder.
func (tc *TasksCreate) Mutation() *TasksMutation {
	return tc.mutation
}

// Save creates the Tasks in the database.
func (tc *TasksCreate) Save(ctx context.Context) (*Tasks, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TasksCreate) SaveX(ctx context.Context) *Tasks {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TasksCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TasksCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TasksCreate) check() error {
	if _, ok := tc.mutation.TaskName(); !ok {
		return &ValidationError{Name: "taskName", err: errors.New(`ent: missing required field "Tasks.taskName"`)}
	}
	if _, ok := tc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Tasks.status"`)}
	}
	return nil
}

func (tc *TasksCreate) sqlSave(ctx context.Context) (*Tasks, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TasksCreate) createSpec() (*Tasks, *sqlgraph.CreateSpec) {
	var (
		_node = &Tasks{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tasks.Table, sqlgraph.NewFieldSpec(tasks.FieldID, field.TypeInt))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.TaskName(); ok {
		_spec.SetField(tasks.FieldTaskName, field.TypeString, value)
		_node.TaskName = value
	}
	if value, ok := tc.mutation.Status(); ok {
		_spec.SetField(tasks.FieldStatus, field.TypeBool, value)
		_node.Status = value
	}
	return _node, _spec
}

// TasksCreateBulk is the builder for creating many Tasks entities in bulk.
type TasksCreateBulk struct {
	config
	err      error
	builders []*TasksCreate
}

// Save creates the Tasks entities in the database.
func (tcb *TasksCreateBulk) Save(ctx context.Context) ([]*Tasks, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tasks, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TasksMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TasksCreateBulk) SaveX(ctx context.Context) []*Tasks {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TasksCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TasksCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
